site_name: CS6332-F2019 @ UTD

# theme:
#    name: mkdocs
#    custom_dir: custom_theme

plugins:
    - search
    - awesome-pages
    - git-revision-date
    - macros

nav:
    # - Home:
    #      - 'index.md'
    - General: 'general.md'
    - Schedule: 'schedule.md'
    - Papers: 'papers.md'
    - Projects: 'projects.md'
    - Assignments:
       - quiz 0x01: 'quiz01.md'
       - assignment 0x01: 'assignment01.md'

markdown_extensions:
    - toc
    - smarty
    - admonition
    # admonition example
    # !!! note
    #     This is a notice!
# macros    
extra:
    course:
        instructor: 'Kangkook Jee'
