site_name: CS6332-F2019 @ UTD

# theme:
#    name: mkdocs
#    custom_dir: custom_theme

plugins:
    - search
    - awesome-pages
    - git-revision-date
    - macros

nav:
    # - Home:
    #      - 'index.md'
    - General: 'general.md'
    - Schedule: 'schedule.md'
    - Papers: 'papers.md'
    - Projects: 'projects.md'
    - Assignments:
        - Assignments: 'assignments.md'
        - quizzes: 'quizzes.md'
    # - Piazza: 'http://www.piazza.com'

markdown_extensions:
    - toc
    - smarty
    - admonition
# macros    
extra:
    course:
        instructor: 'Kangkook Jee'
